server:
  port: 8086

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root

mybatis:
  # 配置 mapper 所在位置
  mapper-locations: classpath:mapper/*.xml
  # sql详细输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
